import {
  Pizza,
  Soup,
  Fish,
  Cake,
  Salad,
  Drumstick,
  EggFried,
  CookingPot,
} from "lucide-react";

export const MENU_DATA = [
  {
    id: 1,
    image: <Pizza size={44} />,
    name: "Margherita Pizza",
    price: "$12",
    details:
      "Classic Italian pizza with fresh tomatoes, mozzarella, and basil.",
    ingredients: [
      { ingredient: "Tomato", quantity: 0.5, units: "lbs", price: "$1.00" },
      { ingredient: "Mozzarella", quantity: 0.2, units: "lbs", price: "$1.50" },
      { ingredient: "Basil", quantity: 5, units: "leaves", price: "$0.50" },
    ],
  },
  {
    id: 2,
    image: <Soup size={44} />,
    name: "Tomato Soup",
    price: "$6",
    details: "Warm and comforting tomato soup with a hint of basil.",
    ingredients: [
      { ingredient: "Tomato", quantity: 0.6, units: "lbs", price: "$1.50" },
      { ingredient: "Garlic", quantity: 1, units: "clove", price: "$0.20" },
      { ingredient: "Basil", quantity: 3, units: "leaves", price: "$0.30" },
    ],
  },
  {
    id: 3,
    image: <CookingPot size={44} />,
    name: "Sushi Platter",
    price: "$20",
    details: "Assortment of fresh sushi rolls and sashimi.",
    ingredients: [
      { ingredient: "Rice", quantity: 0.5, units: "lbs", price: "$1.00" },
      { ingredient: "Salmon", quantity: 0.2, units: "lbs", price: "$3.50" },
      { ingredient: "Seaweed", quantity: 2, units: "sheets", price: "$0.80" },
    ],
  },
  {
    id: 4,
    image: <Drumstick size={44} />,
    name: "Grilled Chicken",
    price: "$15",
    details: "Juicy grilled chicken with herbs and spices.",
    ingredients: [
      {
        ingredient: "Chicken Breast",
        quantity: 1,
        units: "lbs",
        price: "$5.00",
      },
      { ingredient: "Olive Oil", quantity: 2, units: "oz", price: "$0.30" },
      { ingredient: "Herbs", quantity: 1, units: "tsp", price: "$0.20" },
    ],
  },
  {
    id: 5,
    image: <Salad size={44} />,
    name: "Caesar Salad",
    price: "$9",
    details:
      "Crisp romaine lettuce with Caesar dressing, croutons, and parmesan.",
    ingredients: [
      {
        ingredient: "Romaine Lettuce",
        quantity: 0.5,
        units: "lbs",
        price: "$1.00",
      },
      { ingredient: "Croutons", quantity: 1, units: "oz", price: "$0.50" },
      { ingredient: "Parmesan", quantity: 0.1, units: "lbs", price: "$1.00" },
    ],
  },
  {
    id: 6,
    image: <Fish size={44} />,
    name: "Grilled Salmon",
    price: "$18",
    details: "Perfectly grilled salmon served with lemon and herbs.",
    ingredients: [
      { ingredient: "Salmon", quantity: 0.3, units: "lbs", price: "$6.00" },
      { ingredient: "Lemon", quantity: 1, units: "slice", price: "$0.20" },
      { ingredient: "Herbs", quantity: 1, units: "tsp", price: "$0.20" },
    ],
  },
  {
    id: 7,
    image: <Cake size={44} />,
    name: "Cheesecake",
    price: "$7",
    details: "Creamy cheesecake with a graham cracker crust.",
    ingredients: [
      {
        ingredient: "Cream Cheese",
        quantity: 0.5,
        units: "lbs",
        price: "$2.00",
      },
      {
        ingredient: "Graham Crackers",
        quantity: 0.1,
        units: "lbs",
        price: "$0.80",
      },
      { ingredient: "Sugar", quantity: 2, units: "oz", price: "$0.10" },
    ],
  },
  {
    id: 8,
    image: <Pizza size={44} />,
    name: "Lasagna",
    price: "$13",
    details: "Layers of pasta, meat sauce, and cheese, baked to perfection.",
    ingredients: [
      { ingredient: "Pasta Sheets", quantity: 3, units: "pcs", price: "$1.00" },
      {
        ingredient: "Ground Beef",
        quantity: 0.3,
        units: "lbs",
        price: "$2.00",
      },
      { ingredient: "Cheese", quantity: 0.2, units: "lbs", price: "$1.50" },
    ],
  },
  {
    id: 9,
    image: <Salad size={44} />,
    name: "Greek Salad",
    price: "$8",
    details: "Fresh salad with cucumbers, olives, feta cheese, and tomatoes.",
    ingredients: [
      { ingredient: "Cucumber", quantity: 1, units: "pcs", price: "$0.50" },
      { ingredient: "Olives", quantity: 0.1, units: "lbs", price: "$1.00" },
      {
        ingredient: "Feta Cheese",
        quantity: 0.2,
        units: "lbs",
        price: "$1.50",
      },
    ],
  },
  {
    id: 10,
    image: <EggFried size={44} />,
    name: "Ramen",
    price: "$10",
    details: "Japanese noodle soup with a flavorful broth and toppings.",
    ingredients: [
      {
        ingredient: "Ramen Noodles",
        quantity: 0.2,
        units: "lbs",
        price: "$1.00",
      },
      { ingredient: "Broth", quantity: 300, units: "ml", price: "$2.00" },
      {
        ingredient: "Green Onions",
        quantity: 0.1,
        units: "lbs",
        price: "$0.50",
      },
    ],
  },
  {
    id: 11,
    image: <Cake size={44} />,
    name: "Brownie",
    price: "$4",
    details: "Rich and fudgy chocolate brownie.",
    ingredients: [
      { ingredient: "Chocolate", quantity: 4, units: "oz", price: "$1.00" },
      { ingredient: "Butter", quantity: 2, units: "oz", price: "$0.50" },
      { ingredient: "Sugar", quantity: 3, units: "oz", price: "$0.30" },
    ],
  },
  {
    id: 12,
    image: <Soup size={44} />,
    name: "French Onion Soup",
    price: "$7",
    details: "Classic French soup with caramelized onions and cheese.",
    ingredients: [
      { ingredient: "Onions", quantity: 0.4, units: "lbs", price: "$0.80" },
      { ingredient: "Beef Broth", quantity: 300, units: "ml", price: "$1.00" },
      {
        ingredient: "Gruyere Cheese",
        quantity: 0.1,
        units: "lbs",
        price: "$1.50",
      },
    ],
  },
  {
    id: 13,
    image: <Fish size={44} />,
    name: "Fish Tacos",
    price: "$11",
    details: "Tacos filled with crispy fish, slaw, and a creamy sauce.",
    ingredients: [
      {
        ingredient: "Fish Fillet",
        quantity: 0.3,
        units: "lbs",
        price: "$3.00",
      },
      { ingredient: "Tortillas", quantity: 3, units: "pcs", price: "$0.60" },
      { ingredient: "Cabbage", quantity: 0.1, units: "lbs", price: "$0.50" },
    ],
  },
  {
    id: 14,
    image: <Salad size={44} />,
    name: "Quinoa Salad",
    price: "$9",
    details: "Healthy salad with quinoa, veggies, and a light dressing.",
    ingredients: [
      { ingredient: "Quinoa", quantity: 0.2, units: "lbs", price: "$1.20" },
      {
        ingredient: "Bell Pepper",
        quantity: 0.1,
        units: "lbs",
        price: "$0.30",
      },
      { ingredient: "Cucumber", quantity: 0.1, units: "lbs", price: "$0.20" },
    ],
  },
  {
    id: 15,
    image: <EggFried size={44} />,
    name: "Omelette",
    price: "$5",
    details: "Fluffy omelette with cheese and vegetables.",
    ingredients: [
      { ingredient: "Eggs", quantity: 3, units: "pcs", price: "$1.50" },
      { ingredient: "Cheese", quantity: 0.1, units: "lbs", price: "$0.80" },
      {
        ingredient: "Bell Pepper",
        quantity: 0.1,
        units: "lbs",
        price: "$0.20",
      },
    ],
  },
];
