import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import clsx from "clsx";
import "./globals.css";
import Head from "next/head";
import ClientWrapper from "./ClientWrapper"; // Import the client component
import { Providers } from "./providers";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FoodTrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={clsx(dmSans.className, "antialiased")}>
        <ClientWrapper>
          <Providers>{children}</Providers>
        </ClientWrapper>
      </body>
    </html>
  );
}
